### ISSUE TITLE
This generates error on Windows

### ISSUE THREAD

**Issue by adewalegeorge** [iamcdonald/gulp-file-tree#2]
Hi Guys,

I enjoy using this module and it has been amazing on my mac but not on windows. For some reason its generating a JS bug when trying to read through the source directory on windows. Any help please.

**Comment by iamcdonald** [comment]
Hi,

my bad, I hadn't given any thought to the path differences between mac and windows.
However, I've just pushed out a new version (0.4.1) that should address this problem.
Let know how you get on and if it all looks good I'll close the issue.

Thanks,

Iain

**Comment by iamcdonald** [comment]
I'm going to assume this issue is now fixed and close it. However, if you still have any problems please feel free to re-open it or log another issue.
